### ISSUE TITLE
add  CSS to it 

### ISSUE THREAD

**Issue by sakura532** [sakura532/To-Do-list#1]
Make good looking CSS.

**Comment by Harikrishna3** [comment]
Can you assign me I have already did it.

**Comment by sakura532** [comment]
sure

**Comment by Harikrishna3** [comment]
![image](https://user-images.githubusercontent.com/86600101/194744361-654def7b-6823-47cc-957c-02ae7efc909e.png)
plz check this.

**Comment by Harikrishna3** [comment]
![image](https://user-images.githubusercontent.com/86600101/194744446-21242078-10bc-4d33-86ad-5465be187047.png)
plz check this

**Comment by sakura532** [comment]
OK do PR
